services:

  app:
    build:
      context: node
    container_name: app
    networks:
      - custom-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - database

  database:
    ## Enable this line to execute on M1 machines
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: database
    restart: always
    tty: true
    networks:
      - custom-network
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
  
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - custom-network

networks:
  custom-network:

